/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
//    public String getGreeting() {
//        return "Hello world.";
//    }

    public static void main(String[] args) {
    	
    	Car car = new Car("v8","specWheel");
    	car.start();
    	
    	SportCat sportCar = new SportCat("v8","specWheel","solo");
    	sportCar.start();
    	
    	Truck truck = new Truck("v8","specWheel","第三车厢");
    	truck.start();
    	truck.load();
    	
//        System.out.println(new App().getGreeting());
    }
}
